# docker-compose
version: '3.9'
services:
  gprocess_web:
    container_name: 'gprocess_web'
    build:
      context: .
      args:
        - CONFIG=production
    restart: always
    ports:
      - 8080:8080